//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Kids.bmi.ir.KidsScoreServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KidsScoreServiceRef.ScoreServiceSoap")]
    public interface ScoreServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGameScore", ReplyAction="*")]
        void AddGameScore(int GameId, int ScoreId, long Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScoreServiceSoapChannel : Site.Kids.bmi.ir.KidsScoreServiceRef.ScoreServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScoreServiceSoapClient : System.ServiceModel.ClientBase<Site.Kids.bmi.ir.KidsScoreServiceRef.ScoreServiceSoap>, Site.Kids.bmi.ir.KidsScoreServiceRef.ScoreServiceSoap {
        
        public ScoreServiceSoapClient() {
        }
        
        public ScoreServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScoreServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddGameScore(int GameId, int ScoreId, long Value) {
            base.Channel.AddGameScore(GameId, ScoreId, Value);
        }
    }
}
