//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace Kids.EntitiesModel
{
    public partial class BMIKidsEntities : ObjectContext
    {
        public const string ConnectionString = "name=BMIKidsEntities";
        public const string ContainerName = "BMIKidsEntities";
    
        #region Constructors
    
        public BMIKidsEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public BMIKidsEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public BMIKidsEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<NewsCategory> NewsCategories
        {
            get { return _newsCategories  ?? (_newsCategories = CreateObjectSet<NewsCategory>("NewsCategories")); }
        }
        private ObjectSet<NewsCategory> _newsCategories;
    
        public ObjectSet<SystemRole> SystemRoles
        {
            get { return _systemRoles  ?? (_systemRoles = CreateObjectSet<SystemRole>("SystemRoles")); }
        }
        private ObjectSet<SystemRole> _systemRoles;
    
        public ObjectSet<SystemUser> SystemUsers
        {
            get { return _systemUsers  ?? (_systemUsers = CreateObjectSet<SystemUser>("SystemUsers")); }
        }
        private ObjectSet<SystemUser> _systemUsers;
    
        public ObjectSet<DynamicPage> DynamicPages
        {
            get { return _dynamicPages  ?? (_dynamicPages = CreateObjectSet<DynamicPage>("DynamicPages")); }
        }
        private ObjectSet<DynamicPage> _dynamicPages;
    
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get { return _errorLogs  ?? (_errorLogs = CreateObjectSet<ErrorLog>("ErrorLogs")); }
        }
        private ObjectSet<ErrorLog> _errorLogs;
    
        public ObjectSet<GreetingCard> GreetingCards
        {
            get { return _greetingCards  ?? (_greetingCards = CreateObjectSet<GreetingCard>("GreetingCards")); }
        }
        private ObjectSet<GreetingCard> _greetingCards;
    
        public ObjectSet<Kids_Greetings> Kids_Greetings
        {
            get { return _kids_Greetings  ?? (_kids_Greetings = CreateObjectSet<Kids_Greetings>("Kids_Greetings")); }
        }
        private ObjectSet<Kids_Greetings> _kids_Greetings;
    
        public ObjectSet<Kids_Scores> Kids_Scores
        {
            get { return _kids_Scores  ?? (_kids_Scores = CreateObjectSet<Kids_Scores>("Kids_Scores")); }
        }
        private ObjectSet<Kids_Scores> _kids_Scores;
    
        public ObjectSet<Kids_Wishes> Kids_Wishes
        {
            get { return _kids_Wishes  ?? (_kids_Wishes = CreateObjectSet<Kids_Wishes>("Kids_Wishes")); }
        }
        private ObjectSet<Kids_Wishes> _kids_Wishes;
    
        public ObjectSet<ScoreTypeCategory> ScoreTypeCategories
        {
            get { return _scoreTypeCategories  ?? (_scoreTypeCategories = CreateObjectSet<ScoreTypeCategory>("ScoreTypeCategories")); }
        }
        private ObjectSet<ScoreTypeCategory> _scoreTypeCategories;
    
        public ObjectSet<QuestionnaireForm_Questions> QuestionnaireForm_Questions
        {
            get { return _questionnaireForm_Questions  ?? (_questionnaireForm_Questions = CreateObjectSet<QuestionnaireForm_Questions>("QuestionnaireForm_Questions")); }
        }
        private ObjectSet<QuestionnaireForm_Questions> _questionnaireForm_Questions;
    
        public ObjectSet<QuestionnaireForm_UserResponses> QuestionnaireForm_UserResponses
        {
            get { return _questionnaireForm_UserResponses  ?? (_questionnaireForm_UserResponses = CreateObjectSet<QuestionnaireForm_UserResponses>("QuestionnaireForm_UserResponses")); }
        }
        private ObjectSet<QuestionnaireForm_UserResponses> _questionnaireForm_UserResponses;
    
        public ObjectSet<QuestionnaireForm> QuestionnaireForms
        {
            get { return _questionnaireForms  ?? (_questionnaireForms = CreateObjectSet<QuestionnaireForm>("QuestionnaireForms")); }
        }
        private ObjectSet<QuestionnaireForm> _questionnaireForms;
    
        public ObjectSet<QuestionnaireForms_ResponseItems> QuestionnaireForms_ResponseItems
        {
            get { return _questionnaireForms_ResponseItems  ?? (_questionnaireForms_ResponseItems = CreateObjectSet<QuestionnaireForms_ResponseItems>("QuestionnaireForms_ResponseItems")); }
        }
        private ObjectSet<QuestionnaireForms_ResponseItems> _questionnaireForms_ResponseItems;
    
        public ObjectSet<DynamicPageType> DynamicPageTypes
        {
            get { return _dynamicPageTypes  ?? (_dynamicPageTypes = CreateObjectSet<DynamicPageType>("DynamicPageTypes")); }
        }
        private ObjectSet<DynamicPageType> _dynamicPageTypes;
    
        public ObjectSet<ParentRelation> ParentRelations
        {
            get { return _parentRelations  ?? (_parentRelations = CreateObjectSet<ParentRelation>("ParentRelations")); }
        }
        private ObjectSet<ParentRelation> _parentRelations;
    
        public ObjectSet<KidsUser> KidsUsers
        {
            get { return _kidsUsers  ?? (_kidsUsers = CreateObjectSet<KidsUser>("KidsUsers")); }
        }
        private ObjectSet<KidsUser> _kidsUsers;
    
        public ObjectSet<Wish> Wishes
        {
            get { return _wishes  ?? (_wishes = CreateObjectSet<Wish>("Wishes")); }
        }
        private ObjectSet<Wish> _wishes;
    
        public ObjectSet<ScoreType> ScoreTypes
        {
            get { return _scoreTypes  ?? (_scoreTypes = CreateObjectSet<ScoreType>("ScoreTypes")); }
        }
        private ObjectSet<ScoreType> _scoreTypes;
    
        public ObjectSet<BankStoryExam> BankStoryExams
        {
            get { return _bankStoryExams  ?? (_bankStoryExams = CreateObjectSet<BankStoryExam>("BankStoryExams")); }
        }
        private ObjectSet<BankStoryExam> _bankStoryExams;
    
        public ObjectSet<BankStoryExam_Question> BankStoryExam_Question
        {
            get { return _bankStoryExam_Question  ?? (_bankStoryExam_Question = CreateObjectSet<BankStoryExam_Question>("BankStoryExam_Question")); }
        }
        private ObjectSet<BankStoryExam_Question> _bankStoryExam_Question;
    
        public ObjectSet<KidsUser_BankStoryExam> KidsUser_BankStoryExam
        {
            get { return _kidsUser_BankStoryExam  ?? (_kidsUser_BankStoryExam = CreateObjectSet<KidsUser_BankStoryExam>("KidsUser_BankStoryExam")); }
        }
        private ObjectSet<KidsUser_BankStoryExam> _kidsUser_BankStoryExam;
    
        public ObjectSet<FAQCategory> FAQCategories
        {
            get { return _fAQCategories  ?? (_fAQCategories = CreateObjectSet<FAQCategory>("FAQCategories")); }
        }
        private ObjectSet<FAQCategory> _fAQCategories;
    
        public ObjectSet<FAQ> FAQs
        {
            get { return _fAQs  ?? (_fAQs = CreateObjectSet<FAQ>("FAQs")); }
        }
        private ObjectSet<FAQ> _fAQs;
    
        public ObjectSet<KidsUserState> KidsUserStates
        {
            get { return _kidsUserStates  ?? (_kidsUserStates = CreateObjectSet<KidsUserState>("KidsUserStates")); }
        }
        private ObjectSet<KidsUserState> _kidsUserStates;
    
        public ObjectSet<News> News
        {
            get { return _news  ?? (_news = CreateObjectSet<News>("News")); }
        }
        private ObjectSet<News> _news;
    
        public ObjectSet<PostalCard> PostalCards
        {
            get { return _postalCards  ?? (_postalCards = CreateObjectSet<PostalCard>("PostalCards")); }
        }
        private ObjectSet<PostalCard> _postalCards;
    
        public ObjectSet<GeustKidsUser> GeustKidsUsers
        {
            get { return _geustKidsUsers  ?? (_geustKidsUsers = CreateObjectSet<GeustKidsUser>("GeustKidsUsers")); }
        }
        private ObjectSet<GeustKidsUser> _geustKidsUsers;
    
        public ObjectSet<KidsUsers_Payments> KidsUsers_Payments
        {
            get { return _kidsUsers_Payments  ?? (_kidsUsers_Payments = CreateObjectSet<KidsUsers_Payments>("KidsUsers_Payments")); }
        }
        private ObjectSet<KidsUsers_Payments> _kidsUsers_Payments;
    
        public ObjectSet<Game> Games
        {
            get { return _games  ?? (_games = CreateObjectSet<Game>("Games")); }
        }
        private ObjectSet<Game> _games;
    
        public ObjectSet<PollQuestion> PollQuestions
        {
            get { return _pollQuestions  ?? (_pollQuestions = CreateObjectSet<PollQuestion>("PollQuestions")); }
        }
        private ObjectSet<PollQuestion> _pollQuestions;
    
        public ObjectSet<PollResponseItem> PollResponseItems
        {
            get { return _pollResponseItems  ?? (_pollResponseItems = CreateObjectSet<PollResponseItem>("PollResponseItems")); }
        }
        private ObjectSet<PollResponseItem> _pollResponseItems;
    
        public ObjectSet<PollUserResponse> PollUserResponses
        {
            get { return _pollUserResponses  ?? (_pollUserResponses = CreateObjectSet<PollUserResponse>("PollUserResponses")); }
        }
        private ObjectSet<PollUserResponse> _pollUserResponses;
    
        public ObjectSet<Festival> Festivals
        {
            get { return _festivals  ?? (_festivals = CreateObjectSet<Festival>("Festivals")); }
        }
        private ObjectSet<Festival> _festivals;
    
        public ObjectSet<Festival_Pictures> Festival_Pictures
        {
            get { return _festival_Pictures  ?? (_festival_Pictures = CreateObjectSet<Festival_Pictures>("Festival_Pictures")); }
        }
        private ObjectSet<Festival_Pictures> _festival_Pictures;
    
        public ObjectSet<Festival_Pictures_Poll> Festival_Pictures_Poll
        {
            get { return _festival_Pictures_Poll  ?? (_festival_Pictures_Poll = CreateObjectSet<Festival_Pictures_Poll>("Festival_Pictures_Poll")); }
        }
        private ObjectSet<Festival_Pictures_Poll> _festival_Pictures_Poll;

        #endregion
    }
}
