//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Kids.EntitiesModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SystemUser))]
    public partial class SystemRole: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RoleId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _roleId = value;
                    OnPropertyChanged("RoleId");
                }
            }
        }
        private int _roleId;
    
        [DataMember]
        public string RoleName
        {
            get { return _roleName; }
            set
            {
                if (_roleName != value)
                {
                    _roleName = value;
                    OnPropertyChanged("RoleName");
                }
            }
        }
        private string _roleName;
    
        [DataMember]
        public string RoleDescription
        {
            get { return _roleDescription; }
            set
            {
                if (_roleDescription != value)
                {
                    _roleDescription = value;
                    OnPropertyChanged("RoleDescription");
                }
            }
        }
        private string _roleDescription;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<SystemUser> SystemUsers
        {
            get
            {
                if (_systemUsers == null)
                {
                    _systemUsers = new TrackableCollection<SystemUser>();
                    _systemUsers.CollectionChanged += FixupSystemUsers;
                }
                return _systemUsers;
            }
            set
            {
                if (!ReferenceEquals(_systemUsers, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_systemUsers != null)
                    {
                        _systemUsers.CollectionChanged -= FixupSystemUsers;
                    }
                    _systemUsers = value;
                    if (_systemUsers != null)
                    {
                        _systemUsers.CollectionChanged += FixupSystemUsers;
                    }
                    OnNavigationPropertyChanged("SystemUsers");
                }
            }
        }
        private TrackableCollection<SystemUser> _systemUsers;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            SystemUsers.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupSystemUsers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SystemUser item in e.NewItems)
                {
                    if (!item.SystemRoles.Contains(this))
                    {
                        item.SystemRoles.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SystemUsers", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SystemUser item in e.OldItems)
                {
                    if (item.SystemRoles.Contains(this))
                    {
                        item.SystemRoles.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SystemUsers", item);
                    }
                }
            }
        }

        #endregion
    }
}
