//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Kids.bmi.ir.Scores {
    
    
    public partial class PowerKidsUser {
        
        /// <summary>
        /// PowerKidsUserWidget1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Site.Kids.bmi.ir.Scores.PowerKidsUserWidget PowerKidsUserWidget1;
        
        /// <summary>
        /// LastSiteUserWidget1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Site.Kids.bmi.ir.Registration.LastSiteUserWidget LastSiteUserWidget1;
    }
}
